---

- hosts: jenkins
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.java
    - geerlingguy.git
    - geerlingguy.jenkins
    - epel
    - nginx

  tasks:
    - name: Give Jenkins a bash
      user: name=jenkins shell=/bin/bash groups=jenkins

    - name: Generate ssh public key to communicate with Git repo
      user: name=jenkins generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=/var/lib/jenkins/.ssh/id_rsa

    - name: Store ssh public key to use it later
      shell: >
        cat /var/lib/jenkins/.ssh/id_rsa.pub
      register: git_public_key

    - name: Here is your public key to add in git repo
      debug: msg="{{ git_public_key.stdout }}"
      when: git_public_key.stdout is defined
