---

- name: Install nginx
  yum: name=nginx state=latest
  notify: Start nginx

- name: Port forwarding
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=644
  notify: Reload nginx
